steps:
- name: 'gcr.io/cloud-builders/docker'
  id: 'build-backend'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/cerberus-backend:latest', '.']
  dir: 'cerberus_universal_backend'
- name: 'gcr.io/cloud-builders/docker'
  id: 'build-cerberus-frontend'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/cerberus-frontend:latest', '.']
  dir: 'cerberus_frontend'
- name: 'gcr.io/cloud-builders/docker'
  id: 'build-campaign-frontend'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/universal-campaign-frontend:latest', '.']
  dir: 'universal_campaign_frontend'
images:
- 'gcr.io/$PROJECT_ID/cerberus-backend:latest'
- 'gcr.io/$PROJECT_ID/cerberus-frontend:latest'
- 'gcr.io/$PROJECT_ID/universal-campaign-frontend:latest'
