steps:
  # Step 1: Build the Docker image for cerberus_report_backend (agenda-api)
  - name: 'gcr.io/cloud-builders/docker'
    id: 'build-report-backend'
    dir: 'cerberus_report_backend'
    waitFor: ['-']
    args: [
      'build',
      '-t', 'us-south1-docker.pkg.dev/cerberus-data-cloud/cerberus-images/agenda-api:v1', # Updated to Artifact Registry
      '-f', 'Dockerfile',
      '.'
    ]

  # Step 2: Build the Docker image for cerberus_campaigns_backend (campaigns-api)
  - name: 'gcr.io/cloud-builders/docker'
    id: 'build-campaigns-backend'
    dir: 'cerberus_campaigns_backend' # Change working directory to the backend's root
    waitFor: ['-']
    args: [
      'build',
      '-t', 'us-south1-docker.pkg.dev/cerberus-data-cloud/cerberus-images/campaigns-api:latest', # Updated to Artifact Registry
      '-f', 'Dockerfile', # Dockerfile is now in the current context
      '.' # Build context is now cerberus_campaigns_backend
    ]

  # Step 3: Build the Docker image for cerberus_frontend (web-frontend)
  - name: 'gcr.io/cloud-builders/docker'
    id: 'build-cerberus-frontend'
    dir: 'cerberus_frontend'
    waitFor: ['-']
    args: [
      'build',
      '-t', 'us-south1-docker.pkg.dev/cerberus-data-cloud/cerberus-images/cerberus-frontend:latest', # Updated to Artifact Registry
      '-f', 'Dockerfile', # Use the Dockerfile in its specific directory
      '.'
    ]

  # Step 4: Build the Docker image for emmons_frontend (web-frontend)
  - name: 'gcr.io/cloud-builders/docker'
    id: 'build-emmons-frontend'
    dir: 'emmons_frontend'
    args: [
      'build',
      '-t', 'us-south1-docker.pkg.dev/cerberus-data-cloud/cerberus-images/emmons-frontend:latest', # Updated to Artifact Registry
      '-f', 'Dockerfile', # Use the Dockerfile in its specific directory
      '.'
    ]

  # Step 5: Run Database Migrations using a secret for the DATABASE_URL
  - name: 'gcr.io/google-appengine/exec-wrapper'
    id: 'run-migrations'
    waitFor: ['build-campaigns-backend']
    args: [
      '-i', 'us-south1-docker.pkg.dev/cerberus-data-cloud/cerberus-images/campaigns-api:latest',
      '--',
      'flask',
      'db',
      'upgrade'
    ]
    secretEnv: ['DATABASE_URL']

# List of images to be pushed to Artifact Registry
images:
  - 'us-south1-docker.pkg.dev/cerberus-data-cloud/cerberus-images/agenda-api:v1'
  - 'us-south1-docker.pkg.dev/cerberus-data-cloud/cerberus-images/campaigns-api:latest'
  - 'us-south1-docker.pkg.dev/cerberus-data-cloud/cerberus-images/cerberus-frontend:latest'
  - 'us-south1-docker.pkg.dev/cerberus-data-cloud/cerberus-images/emmons-frontend:latest'

# Specify the service account for Cloud Build to use for executing these steps
# Ensure this service account has 'Artifact Registry Writer' role for the project or specifically for the 'cerberus-images' repository.
serviceAccount: 'projects/cerberus-data-cloud/serviceAccounts/cerberus-service-account@cerberus-data-cloud.iam.gserviceaccount.com'

# Explicitly set logging options as required when a custom service account is used.
options:
  logging: CLOUD_LOGGING_ONLY

# Define the secrets to be used in the build
secrets:
- secretEnv:
    DATABASE_URL:
      secretName: CAMPAIGNS_DATABASE_URL
      versionName: latest

# Specify the service account for Cloud Build to use for executing these steps
# Ensure this service account has 'Artifact Registry Writer' role for the project or specifically for the 'cerberus-images' repository.
serviceAccount: 'projects/cerberus-data-cloud/serviceAccounts/cerberus-service-account@cerberus-data-cloud.iam.gserviceaccount.com'

# Explicitly set logging options as required when a custom service account is used.
options:
  logging: CLOUD_LOGGING_ONLY