steps:
# Build and deploy the backend
- name: 'gcr.io/cloud-builders/docker'
  id: 'Build Backend Docker Image'
  args: [ 'build', '-t', '${_REGION}-docker.pkg.dev/$PROJECT_ID/cerberus-images/cerberus-backend:$BUILD_ID', './cerberus_universal_backend' ]

- name: 'gcr.io/cloud-builders/docker'
  id: 'Push Backend Docker Image'
  args: [ 'push', '${_REGION}-docker.pkg.dev/$PROJECT_ID/cerberus-images/cerberus-backend:$BUILD_ID' ]
  waitFor: ['Build Backend Docker Image']

- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  id: 'Deploy Backend to Cloud Run'
  entrypoint: gcloud
  args:
    - 'run'
    - 'deploy'
    - 'cerberus-backend'
    - '--image'
    - '${_REGION}-docker.pkg.dev/$PROJECT_ID/cerberus-images/cerberus-backend:$BUILD_ID'
    - '--region'
    - '${_REGION}'
    - '--platform'
    - 'managed'
    - '--allow-unauthenticated'
    - '--add-cloudsql-instances'
    - '${_INSTANCE_CONNECTION_NAME}'
    - '--set-secrets=DB_USER=DB_USER:latest,DB_PASS=DB_PASSWORD:latest,DB_NAME=DB_NAME:latest,DB_CONNECTION_NAME=DB_CONNECTION_NAME:latest,FLASK_SECRET_KEY=FLASK_SECRET_KEY:latest,PGCRYPTO_SECRET_KEY=PGCRYPTO_SECRET_KEY:latest,BLAIR_STRIPE_SECRET_KEY=BLAIR_STRIPE_SECRET_KEY:latest,COX_STRIPE_SECRET_KEY=COX_STRIPE_SECRET_KEY:latest,EMMONS_STRIPE_SECRET_KEY=EMMONS_STRIPE_SECRET_KEY:latest,GAUNTT_STRIPE_SECRET_KEY=GAUNTT_STRIPE_SECRET_KEY:latest,MINTZ_STRIPE_SECRET_KEY=MINTZ_STRIPE_SECRET_KEY:latest,TICE_STRIPE_SECRET_KEY=TICE_STRIPE_SECRET_KEY:latest,TULLOCH_STRIPE_SECRET_KEY=TULLOCH_STRIPE_SECRET_KEY:latest,LEUDEKE_STRIPE_SECRET_KEY=LEUDEKE_STRIPE_SECRET_KEY:latest,WHITSON_STRIPE_SECRET_KEY=WHITSON_STRIPE_SECRET_KEY:latest,BLAIR_STRIPE_WEBHOOK_KEY=BLAIR_STRIPE_WEBHOOK_KEY:latest,COX_STRIPE_WEBHOOK_KEY=COX_STRIPE_WEBHOOK_KEY:latest,EMMONS_STRIPE_WEBHOOK_KEY=EMMONS_STRIPE_WEBHOOK_KEY:latest,GAUNTT_STRIPE_WEBHOOK_KEY=GAUNTT_STRIPE_WEBHOOK_KEY:latest,MINTZ_STRIPE_WEBHOOK_KEY=MINTZ_STRIPE_WEBHOOK_KEY:latest,TICE_STRIPE_WEBHOOK_KEY=TICE_STRIPE_WEBHOOK_KEY:latest,WHITSON_STRIPE_WEBHOOK_KEY=WHITSON_STRIPE_WEBHOOK_KEY:latest'
  waitFor: ['Push Backend Docker Image']

# Install Flutter SDK once and cache it for both frontends
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  id: 'Install and Cache Flutter SDK'
  entrypoint: 'bash'
  args:
    - '-c'
    - |
      # Check if Flutter SDK is already cached
      if [ -d "/flutter/bin" ] && command -v /flutter/bin/flutter &> /dev/null;
      then
        echo "Flutter SDK already exists in cache. Skipping download."
        /flutter/bin/flutter doctor
      else
        echo "Flutter SDK not found in cache. Cloning and installing..."
        apt-get update && apt-get install -y git unzip # Install git, unzip for cloning, and dart sdk extraction
        git clone https://github.com/flutter/flutter.git /flutter
        git config --global --add safe.directory /flutter # Add safe directory for git ownership issue
        cd /flutter
        git checkout 3.35.1
        ./bin/flutter --version # Check Flutter version
        ./bin/flutter upgrade
        echo "Running flutter doctor..."
        ./bin/flutter doctor
      fi

# Install common dependencies
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  id: 'Install Dependencies'
  entrypoint: 'bash'
  args:
    - '-c'
    - |
      apt-get update && apt-get install -y nodejs npm unzip
      npm install -g firebase-tools@13.11.2
  waitFor: ['Install and Cache Flutter SDK']

# Build and deploy the cerberus_frontend
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  id: 'Get dependencies for Cerberus Frontend'
  entrypoint: 'bash'
  args:
    - '-c'
    - |
      export PATH="/flutter/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin" # Add flutter to PATH
      flutter pub get
  dir: 'cerberus_frontend'
  waitFor: ['Install Dependencies']

- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  id: 'Build Cerberus Frontend'
  entrypoint: 'bash'
  args:
    - '-c'
    - |
      export PATH="/flutter/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin" # Add flutter to PATH
      flutter build web --release
  dir: 'cerberus_frontend'
  waitFor: ['Get dependencies for Cerberus Frontend']

- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  id: 'Deploy Cerberus Frontend'
  entrypoint: 'bash'
  args:
    - '-c'
    - |
      npx firebase-tools deploy --only 'hosting:cerberus' --project 'cerberus-data-cloud'
  waitFor: ['Build Cerberus Frontend']

# Build and deploy all campaign frontends
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  id: 'Build and Deploy All Campaigns'
  entrypoint: 'bash'
  args:
    - '-c'
    - |
      export PATH="/flutter/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
      apt-get update && apt-get install -y nodejs npm unzip
      npm install -g firebase-tools@13.11.2
      chmod +x build_campaigns.sh
      ./build_campaigns.sh
  dir: 'universal_campaign_frontend'
  waitFor: ['Install Dependencies']

images:
- '${_REGION}-docker.pkg.dev/$PROJECT_ID/cerberus-images/cerberus-backend:$BUILD_ID'

options:
  substitution_option: 'ALLOW_LOOSE'
  volumes:
    - name: 'flutter_sdk'
      path: '/flutter'
substitutions:
  _REGION: 'us-south1'
  _INSTANCE_CONNECTION_NAME: 'cerberus-data-cloud:us-south1:cerberus-db'
  _PROJECT_ID: 'cerberus-data-cloud'
  _FLUTTER_VERSION: '3.35.1'
