
include: package:flutter_lints/flutter.yaml

linter:
  rules:
    avoid_print: true
    prefer_single_quotes: true
    prefer_const_constructors: true
    prefer_const_declarations: true
    prefer_final_fields: true
    camel_case_types: true
    library_private_types_in_public_api: true
    non_constant_identifier_names: true
    slash_for_doc_comments: true
    unnecessary_const: true
    unnecessary_new: true
    unnecessary_this: true
    use_key_in_widget_constructors: true
    sized_box_for_whitespace: false
