name: universal_campaign_frontend
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  go_router: ^14.1.1
  cupertino_icons: ^1.0.6
  web: ^1.0.0
  http: ^1.2.1
  flutter_stripe: ^11.5.0
  provider: ^6.0.0
  get_it: ^7.2.0
  google_fonts: ^6.2.1
  url_launcher: ^6.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/logos/
    - assets/icons/
