name: app
description: The main application.

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  campaign_feature:
    path: packages/campaign_feature
  data_portal_feature:
    path: packages/data_portal_feature
  report_feature:
    path: packages/report_feature
  go_router: ^14.6.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
