name: report_feature
description: A feature-specific package for the Cerberus report page.

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  shared_ui:
    path: ../shared_ui
  go_router: ^14.6.2
  http: ^1.2.1
  intl: ^0.20.2
  video_player: ^2.8.6


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
