name: emmons_frontend
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.8.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  
  cupertino_icons: ^1.0.6
  http: ^1.2.1
  flutter_riverpod: ^2.6.1
  flutter_svg: ^2.0.10+1
  go_router: ^16.0.0
  url_launcher: ^6.3.2
  js: ^0.7.1
  
  flutter_web_plugins:
    sdk: flutter
  web: ^1.1.1
  flutter_stripe: ^10.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/fonts/

  fonts:
    - family: BebasNeue
      fonts:
        - asset: assets/fonts/BebasNeue-Regular.ttf
