""""update"

Revision ID: 396b1d5ae908
Revises: d5a18142fd3a
Create Date: 2025-07-29 22:03:51.842247

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '396b1d5ae908'
down_revision = 'd5a18142fd3a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('donations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('stripe_payment_intent_id', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('is_recurring', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('covers_fees', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('stripe_customer_id', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('stripe_subscription_id', sa.String(length=255), nullable=True))
        batch_op.drop_constraint(batch_op.f('donations_stripe_checkout_session_id_key'), type_='unique')
        batch_op.create_unique_constraint(None, ['stripe_payment_intent_id'])
        batch_op.create_unique_constraint(None, ['stripe_subscription_id'])
        batch_op.drop_column('stripe_checkout_session_id')

    with op.batch_alter_table('voters', schema=None) as batch_op:
        batch_op.add_column(sa.Column('contact_email', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('contact_phone', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('contact_mail', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('contact_sms', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('voters', schema=None) as batch_op:
        batch_op.drop_column('contact_sms')
        batch_op.drop_column('contact_mail')
        batch_op.drop_column('contact_phone')
        batch_op.drop_column('contact_email')

    with op.batch_alter_table('donations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('stripe_checkout_session_id', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_unique_constraint(batch_op.f('donations_stripe_checkout_session_id_key'), ['stripe_checkout_session_id'], postgresql_nulls_not_distinct=False)
        batch_op.drop_column('stripe_subscription_id')
        batch_op.drop_column('stripe_customer_id')
        batch_op.drop_column('covers_fees')
        batch_op.drop_column('is_recurring')
        batch_op.drop_column('stripe_payment_intent_id')

    # ### end Alembic commands ###
